import html
from typing import Dict, Any, List, Optional
from datetime import datetime

class ReportGenerator:
    @staticmethod
    def _apply_language(content: str, language: str) -> str:
        """Localiza el HTML independiente sin alterar valores medidos ni identificadores."""
        if language == "es":
            return content
        translations = {
            "en": {
                "Informe de diagnóstico": "Diagnostic report", "Informe Técnico": "Technical report",
                "Resumen de Diagnóstico para el Conductor": "Driver diagnostic summary",
                "Imprimir o guardar en PDF": "Print or save as PDF", "Ver datos técnicos completos": "View full technical data",
                "RESULTADO PRINCIPAL": "MAIN RESULT", "Averías ECU": "ECU faults", "Consumo medio": "Average consumption",
                "Duración analizada": "Analysed duration", "Calidad de la prueba": "Test quality",
                "Estado por sistemas": "System status", "Qué hacer ahora": "What to do next",
                "Averías registradas": "Recorded faults", "Datos principales del trayecto": "Main trip data",
                "Dato": "Data", "Mínimo": "Minimum", "Promedio": "Average", "Máximo": "Maximum",
                "Qué significa este informe": "What this report means", "Vehículo": "Vehicle", "Motor": "Engine",
                "ID de Sesión": "Session ID", "Puntuación de Calidad": "Quality score", "Fecha de Generación": "Generated on",
                "Conclusión": "Conclusion", "Siguientes pasos": "Next steps", "Código": "Code", "Estado": "Status",
                "Descripción": "Description", "Códigos de Avería Registrados": "Recorded fault codes",
                "Hallazgos Deterministas (Motor de Reglas)": "Deterministic findings (rules engine)",
                "Resumen Estadístico de Señales": "Signal statistics summary", "Señal (PID)": "Signal (PID)",
                "Desviación Estándar": "Standard deviation", "Análisis Asistido por Inteligencia Artificial": "AI-assisted analysis",
                "Nivel de Confianza": "Confidence level", "Hechos Observados": "Observed facts",
                "Hipótesis Técnicas": "Technical hypotheses", "Comprobaciones Recomendadas": "Recommended checks",
                "Generado automáticamente por": "Automatically generated by", "Generado el": "Generated on",
                "lecturas válidas": "valid readings", "señales con datos": "signals with data", "No calculable": "Not calculable",
                "Sin códigos de avería": "No fault codes", "No se registraron averías en la ECU.": "No ECU faults were recorded.",
                "Sin datos": "No data", "Correcto": "OK", "Revisar": "Check", "Urgente": "Urgent",
            },
            "it": {
                "Informe de diagnóstico": "Rapporto diagnostico", "Informe Técnico": "Rapporto tecnico",
                "Resumen de Diagnóstico para el Conductor": "Riepilogo diagnostico per il conducente",
                "Imprimir o guardar en PDF": "Stampa o salva in PDF", "Ver datos técnicos completos": "Vedi tutti i dati tecnici",
                "RESULTADO PRINCIPAL": "RISULTATO PRINCIPALE", "Averías ECU": "Guasti ECU", "Consumo medio": "Consumo medio",
                "Duración analizada": "Durata analizzata", "Calidad de la prueba": "Qualità del test",
                "Estado por sistemas": "Stato dei sistemi", "Qué hacer ahora": "Cosa fare ora",
                "Averías registradas": "Guasti registrati", "Datos principales del trayecto": "Dati principali del viaggio",
                "Dato": "Dato", "Mínimo": "Minimo", "Promedio": "Media", "Máximo": "Massimo",
                "Qué significa este informe": "Cosa significa questo rapporto", "Vehículo": "Veicolo", "Motor": "Motore",
                "ID de Sesión": "ID sessione", "Puntuación de Calidad": "Punteggio qualità", "Fecha de Generación": "Data di generazione",
                "Conclusión": "Conclusione", "Siguientes pasos": "Passi successivi", "Código": "Codice", "Estado": "Stato",
                "Descripción": "Descrizione", "Códigos de Avería Registrados": "Codici guasto registrati",
                "Hallazgos Deterministas (Motor de Reglas)": "Riscontri deterministici (motore di regole)",
                "Resumen Estadístico de Señales": "Riepilogo statistico dei segnali", "Señal (PID)": "Segnale (PID)",
                "Desviación Estándar": "Deviazione standard", "Análisis Asistido por Inteligencia Artificial": "Analisi assistita dall'IA",
                "Nivel de Confianza": "Livello di confidenza", "Hechos Observados": "Fatti osservati",
                "Hipótesis Técnicas": "Ipotesi tecniche", "Comprobaciones Recomendadas": "Controlli consigliati",
                "Generado automáticamente por": "Generato automaticamente da", "Generado el": "Generato il",
                "lecturas válidas": "letture valide", "señales con datos": "segnali con dati", "No calculable": "Non calcolabile",
                "Sin códigos de avería": "Nessun codice guasto", "No se registraron averías en la ECU.": "Nessun guasto registrato nella ECU.",
                "Sin datos": "Nessun dato", "Correcto": "Corretto", "Revisar": "Controllare", "Urgente": "Urgente",
            },
            "de": {
                "Informe de diagnóstico": "Diagnosebericht", "Informe Técnico": "Technischer Bericht",
                "Resumen de Diagnóstico para el Conductor": "Diagnoseübersicht für den Fahrer",
                "Imprimir o guardar en PDF": "Drucken oder als PDF speichern", "Ver datos técnicos completos": "Vollständige technische Daten anzeigen",
                "RESULTADO PRINCIPAL": "HAUPTERGEBNIS", "Averías ECU": "ECU-Fehler", "Consumo medio": "Durchschnittsverbrauch",
                "Duración analizada": "Analysierte Dauer", "Calidad de la prueba": "Testqualität",
                "Estado por sistemas": "Systemstatus", "Qué hacer ahora": "Nächste Schritte",
                "Averías registradas": "Gespeicherte Fehler", "Datos principales del trayecto": "Wichtigste Fahrtdaten",
                "Dato": "Messwert", "Mínimo": "Minimum", "Promedio": "Mittelwert", "Máximo": "Maximum",
                "Qué significa este informe": "Was dieser Bericht bedeutet", "Vehículo": "Fahrzeug", "Motor": "Motor",
                "ID de Sesión": "Sitzungs-ID", "Puntuación de Calidad": "Qualitätswert", "Fecha de Generación": "Erstellt am",
                "Conclusión": "Fazit", "Siguientes pasos": "Nächste Schritte", "Código": "Code", "Estado": "Status",
                "Descripción": "Beschreibung", "Códigos de Avería Registrados": "Gespeicherte Fehlercodes",
                "Hallazgos Deterministas (Motor de Reglas)": "Deterministische Befunde (Regelmodul)",
                "Resumen Estadístico de Señales": "Statistische Signalübersicht", "Señal (PID)": "Signal (PID)",
                "Desviación Estándar": "Standardabweichung", "Análisis Asistido por Inteligencia Artificial": "KI-gestützte Analyse",
                "Nivel de Confianza": "Konfidenzniveau", "Hechos Observados": "Beobachtete Fakten",
                "Hipótesis Técnicas": "Technische Hypothesen", "Comprobaciones Recomendadas": "Empfohlene Prüfungen",
                "Generado automáticamente por": "Automatisch erstellt von", "Generado el": "Erstellt am",
                "lecturas válidas": "gültige Messwerte", "señales con datos": "Signale mit Daten", "No calculable": "Nicht berechenbar",
                "Sin códigos de avería": "Keine Fehlercodes", "No se registraron averías en la ECU.": "Keine ECU-Fehler gespeichert.",
                "Sin datos": "Keine Daten", "Correcto": "In Ordnung", "Revisar": "Prüfen", "Urgente": "Dringend",
            },
        }
        localized = content.replace('<html lang="es">', f'<html lang="{language}">')
        for source, target in sorted(translations.get(language, {}).items(), key=lambda item: len(item[0]), reverse=True):
            localized = localized.replace(source, target)
        return localized

    @staticmethod
    def generate_html_report(vehicle: Dict[str, Any], session: Dict[str, Any],
                             stats: Dict[str, Any], findings: List[Dict[str, Any]],
                             ai_analysis: Optional[Dict[str, Any]] = None,
                             dtcs: Optional[List[Dict[str, Any]]] = None,
                             mode: str = "technical",
                             quality_score: Optional[Dict[str, Any]] = None,
                             evidences: Optional[List[Dict[str, Any]]] = None,
                             diagnostic_summary: Optional[Dict[str, Any]] = None,
                             language: str = "es") -> str:
        """Genera una cadena HTML independiente en modo 'user' (sencillo) o 'technical' (taller completo)."""

        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        v_name = html.escape(str(vehicle.get("display_name", "Vehículo")))
        v_make = html.escape(str(vehicle.get("make", "")))
        v_model = html.escape(str(vehicle.get("model", "")))
        v_engine = html.escape(str(vehicle.get("engine", "")))
        v_fuel = html.escape(str(vehicle.get("fuel_type", "")))
        s_id = html.escape(str(session.get("id", "")))

        q_val = quality_score.get("overall_score", 100.0) if quality_score else session.get("capture_quality_score", 100.0)
        q_color = "#10b981" if q_val >= 80 else ("#f59e0b" if q_val >= 50 else "#e11d48")

        if mode == "user":
            summary = diagnostic_summary or {}
            conclusion = summary.get("conclusion", {})
            verdict = str(conclusion.get("verdict", "ok"))
            verdict_color = {
                "ok": "#15803d", "limited": "#a16207", "attention": "#c2410c",
                "urgent": "#b91c1c", "invalid": "#64748b",
            }.get(verdict, "#64748b")
            verdict_title = html.escape(str(conclusion.get("title", "Resultado del diagnóstico")))
            verdict_text = html.escape(str(conclusion.get("summary", "No hay una conclusión disponible.")))

            next_steps = conclusion.get("next_steps") or ["Conserva el informe para comparar futuras pruebas."]
            next_steps_html = "".join(f"<li>{html.escape(str(step))}</li>" for step in next_steps)

            dtc_count = len(dtcs or [])
            dtc_detail = "Sin códigos de avería" if not dtc_count else f"{dtc_count} código(s) registrado(s)"
            dtc_list = "".join(
                f"<li><strong>{html.escape(str(item.get('code', 'DTC')))}</strong> — {html.escape(str(item.get('description', 'Sin descripción')))}</li>"
                for item in (dtcs or [])
            ) or "<li>No se registraron averías en la ECU.</li>"

            health_cards = ""
            health_labels = {"green": "Correcto", "amber": "Revisar", "red": "Urgente", "unknown": "Sin datos"}
            for system in summary.get("health", []):
                status = str(system.get("status", "unknown"))
                if status == "unknown":
                    continue
                health_cards += (
                    f"<article class='system system--{status}'>"
                    f"<span>{html.escape(health_labels.get(status, 'Sin datos'))}</span>"
                    f"<strong>{html.escape(str(system.get('label', 'Sistema')))}</strong>"
                    f"<p>{html.escape(str(system.get('reason', 'Sin información suficiente.')))}</p>"
                    "</article>"
                )

            trip = summary.get("trip_metrics") or {}
            average = trip.get("average_l_per_100km")
            average_text = f"{float(average):.1f} L/100 km" if trip.get("available") and average is not None else "No calculable"
            average_note = html.escape(str(trip.get("reason", "Faltan velocidad o caudal de combustible.")))

            duration = float(stats.get("duration_sec", 0.0) or 0.0)
            duration_text = f"{int(duration // 60)} min {int(duration % 60)} s"
            valid_samples = int(stats.get("valid_samples", 0) or 0)
            measured_signals = sum(1 for item in stats.get("signals", {}).values() if item.get("has_data"))

            friendly = {
                "RPM": "Revoluciones del motor", "SPEED": "Velocidad", "COOLANT_TEMP": "Refrigerante",
                "VAG_OIL_TEMP": "Aceite", "VAG_FUEL_RATE": "Caudal de combustible",
                "VAG_ECU_VOLTAGE": "Tensión de la ECU", "VAG_TORSION_VALUE": "Sincronización de distribución",
            }
            key_rows = ""
            for pid, label in friendly.items():
                signal = stats.get("signals", {}).get(pid, {})
                if not signal.get("has_data"):
                    continue
                unit = html.escape(str(signal.get("unit", "")))
                key_rows += (
                    f"<tr><td>{html.escape(label)}</td><td>{signal.get('min')} {unit}</td>"
                    f"<td>{signal.get('mean')} {unit}</td><td>{signal.get('max')} {unit}</td></tr>"
                )
            key_rows = key_rows or "<tr><td colspan='4'>No hay señales principales suficientes.</td></tr>"

            report = f"""<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Informe de diagnóstico — {v_name}</title>
  <style>
    :root {{ color-scheme:light; --ink:#172033; --muted:#64748b; --line:#dbe3ec; --panel:#fff; }}
    * {{ box-sizing:border-box; }} body {{ margin:0; background:#f1f5f9; color:var(--ink); font-family:Inter,"Segoe UI",Arial,sans-serif; line-height:1.5; }}
    main {{ max-width:980px; margin:0 auto; padding:32px 22px 56px; }}
    header,.card {{ background:var(--panel); border:1px solid var(--line); border-radius:16px; padding:24px; margin-bottom:18px; }}
    h1 {{ margin:0 0 6px; font-size:1.75rem; }} h2 {{ margin:0 0 16px; font-size:1.15rem; }} p {{ margin:.4rem 0; }}
    .muted {{ color:var(--muted); }} .verdict {{ border-left:7px solid {verdict_color}; }} .verdict h2 {{ color:{verdict_color}; font-size:1.5rem; }}
    .metrics {{ display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin:18px 0; }}
    .metric {{ background:#f8fafc; border:1px solid var(--line); border-radius:12px; padding:14px; }}
    .metric span,.system span {{ display:block; color:var(--muted); font-size:.75rem; font-weight:700; text-transform:uppercase; letter-spacing:.04em; }}
    .metric strong {{ display:block; font-size:1.25rem; margin-top:4px; }}
    .systems {{ display:grid; grid-template-columns:repeat(3,1fr); gap:12px; }} .system {{ border:1px solid var(--line); border-top:5px solid #94a3b8; border-radius:12px; padding:14px; }}
    .system--green {{ border-top-color:#22c55e; }} .system--amber {{ border-top-color:#f59e0b; }} .system--red {{ border-top-color:#ef4444; }} .system p {{ color:var(--muted); font-size:.88rem; }}
    table {{ width:100%; border-collapse:collapse; }} th,td {{ padding:10px; border-bottom:1px solid var(--line); text-align:left; }} th {{ color:var(--muted); font-size:.78rem; text-transform:uppercase; }}
    ol,ul {{ padding-left:22px; }} details {{ margin-top:16px; }} summary {{ cursor:pointer; font-weight:700; color:#0369a1; }}
    .actions {{ display:flex; gap:10px; margin-bottom:18px; }} .actions a,.actions button {{ border:0; border-radius:9px; padding:10px 14px; background:#0f172a; color:#fff; text-decoration:none; cursor:pointer; }}
    @media(max-width:720px) {{ .metrics,.systems {{ grid-template-columns:1fr 1fr; }} }}
    @media print {{ body {{ background:#fff; }} main {{ max-width:none; padding:0; }} .actions {{ display:none; }} .card,header {{ break-inside:avoid; box-shadow:none; }} }}
  </style>
</head>
<body><main>
  <div class="actions"><button onclick="window.print()">Imprimir o guardar en PDF</button><a href="?mode=technical">Ver datos técnicos completos</a></div>
  <header><span class="muted">Resumen de Diagnóstico para el Conductor</span><h1>{v_name}</h1><p>{v_make} {v_model} · {v_engine}</p><p class="muted">Generado el {now_str}</p></header>
  <section class="card verdict"><span class="muted">RESULTADO PRINCIPAL</span><h2>{verdict_title}</h2><p>{verdict_text}</p></section>
  <section class="metrics">
    <div class="metric"><span>Averías ECU</span><strong>{dtc_count}</strong><small>{dtc_detail}</small></div>
    <div class="metric"><span>Consumo medio</span><strong>{average_text}</strong><small>{average_note}</small></div>
    <div class="metric"><span>Duración analizada</span><strong>{duration_text}</strong><small>{valid_samples} lecturas válidas</small></div>
    <div class="metric"><span>Calidad de la prueba</span><strong>{q_val:.0f}/100</strong><small>{measured_signals} señales con datos</small></div>
  </section>
  <section class="card"><h2>Estado por sistemas</h2><div class="systems">{health_cards}</div></section>
  <section class="card"><h2>Qué hacer ahora</h2><ol>{next_steps_html}</ol></section>
  <section class="card"><h2>Averías registradas</h2><ul>{dtc_list}</ul></section>
  <section class="card"><h2>Datos principales del trayecto</h2><table><thead><tr><th>Dato</th><th>Mínimo</th><th>Promedio</th><th>Máximo</th></tr></thead><tbody>{key_rows}</tbody></table>
    <details><summary>Qué significa este informe</summary><p class="muted">El resultado se basa solo en las señales que la ECU proporcionó. Una tarjeta «Sin datos» no significa avería: significa que esa parte no pudo evaluarse en esta prueba.</p></details>
  </section>
</main></body></html>"""
            return ReportGenerator._apply_language(report, language)

        # --- MODO TÉCNICO (COMPLETO DE TALLER) ---
        dtc_rows = ""
        if dtcs:
            for d in dtcs:
                c = html.escape(str(d.get("code", "")))
                st = html.escape(str(d.get("status", "")))
                desc = html.escape(str(d.get("description", "")))
                dtc_rows += f"<tr><td><strong style='color:#e11d48;'>{c}</strong></td><td>{st}</td><td>{desc}</td></tr>"
        else:
            dtc_rows = "<tr><td colspan='3' style='color:#10b981;'>Sin códigos de avería almacenados.</td></tr>"

        findings_html = ""
        if findings:
            for f in findings:
                r_id = html.escape(str(f.get("rule_id", "")))
                msg = html.escape(str(f.get("message", "")))
                findings_html += f"<div style='background:#fef3c7; border-left:4px solid #f59e0b; padding:10px; margin-bottom:8px; border-radius:4px;'><strong>{r_id}</strong>: {msg}</div>"
        else:
            findings_html = "<p style='color:#10b981;'>No se han detectado anomalías deterministas por el motor de reglas.</p>"

        signals_html = ""
        signals = stats.get("signals", {})
        for pid, s in signals.items():
            if s.get("has_data"):
                p_name = html.escape(str(pid))
                u = html.escape(str(s.get("unit", "")))
                signals_html += f"<tr><td><strong>{p_name}</strong></td><td>{s.get('min')} {u}</td><td>{s.get('max')} {u}</td><td>{s.get('mean')} {u}</td><td>{s.get('std')}</td></tr>"
        if not signals_html:
            signals_html = (
                "<tr><td colspan='5' style='color:#f59e0b;'>"
                "No hay lecturas OBD válidas en esta sesión. Comprueba la conexión del adaptador y repite la captura."
                "</td></tr>"
            )

        ai_html = ""
        if ai_analysis:
            facts = "".join([f"<li>{html.escape(str(x))}</li>" for x in ai_analysis.get("observed_facts", [])])
            hypotheses = "".join([f"<li>{html.escape(str(x))}</li>" for x in ai_analysis.get("hypotheses", [])])
            checks = "".join([f"<li>{html.escape(str(x))}</li>" for x in ai_analysis.get("recommended_checks", [])])

            ai_html = f"""
            <div style="background:#f8fafc; border:1px solid #cbd5e1; border-radius:8px; padding:16px; margin-top:20px;">
                <h3 style="color:#0284c7; margin-top:0;">🤖 Análisis Asistido por Inteligencia Artificial</h3>
                <p><strong>Nivel de Confianza:</strong> {int(ai_analysis.get('confidence_level', 0.8)*100)}%</p>
                <h4>Hechos Observados:</h4><ul>{facts}</ul>
                <h4>Hipótesis Técnicas:</h4><ul>{hypotheses}</ul>
                <h4>Comprobaciones Recomendadas:</h4><ul>{checks}</ul>
            </div>
            """

        conclusion_html = ""
        if diagnostic_summary:
            conclusion = diagnostic_summary.get("conclusion", {})
            next_steps = "".join(
                f"<li>{html.escape(str(step))}</li>"
                for step in conclusion.get("next_steps", [])
            )
            verdict = html.escape(str(conclusion.get("title", "Resultado de la sesión")))
            summary_text = html.escape(str(conclusion.get("summary", "")))
            conclusion_html = f"""
            <div style="background:#0f172a; color:#f8fafc; border-left:5px solid {q_color}; border-radius:8px; padding:18px; margin:20px 0;">
                <h2 style="color:#f8fafc; margin-top:0;">Conclusión: {verdict}</h2>
                <p>{summary_text}</p>
                <h3 style="color:#cbd5e1;">Siguientes pasos</h3>
                <ol>{next_steps}</ol>
            </div>
            """

        report = f"""<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Informe Técnico — {v_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1e293b; padding: 40px; max-width: 900px; margin: 0 auto; background-color: #ffffff; }}
        h1 {{ color: #0f172a; border-bottom: 2px solid #0284c7; padding-bottom: 8px; }}
        h2 {{ color: #334155; margin-top: 24px; font-size: 1.2rem; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
        th, td {{ padding: 10px; border: 1px solid #e2e8f0; text-align: left; font-size: 0.9rem; }}
        th {{ background-color: #f1f5f9; color: #475569; }}
        .header-meta {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; background: #f8fafc; padding: 16px; border-radius: 8px; margin-bottom: 20px; }}
        .footer {{ margin-top: 40px; font-size: 0.8rem; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px; }}
    </style>
</head>
<body>
    <h1>🚗 Informe Técnico de Diagnóstico OBD-II</h1>
    <div class="header-meta">
        <div>
            <p><strong>Vehículo:</strong> {v_name} ({v_make} {v_model})</p>
            <p><strong>Motor:</strong> {v_engine} ({v_fuel})</p>
        </div>
        <div>
            <p><strong>ID de Sesión:</strong> {s_id}</p>
            <p><strong>Puntuación de Calidad:</strong> <span style="color:{q_color}; font-weight:bold;">{q_val}/100</span></p>
            <p><strong>Fecha de Generación:</strong> {now_str}</p>
        </div>
    </div>

    {conclusion_html}

    <h2>1. Códigos de Avería Registrados (DTC)</h2>
    <table>
        <thead><tr><th>Código</th><th>Estado</th><th>Descripción</th></tr></thead>
        <tbody>{dtc_rows}</tbody>
    </table>

    <h2>2. Hallazgos Deterministas (Motor de Reglas)</h2>
    {findings_html}

    <h2>3. Resumen Estadístico de Señales</h2>
    <table>
        <thead><tr><th>Señal (PID)</th><th>Mínimo</th><th>Máximo</th><th>Promedio</th><th>Desviación Estándar</th></tr></thead>
        <tbody>{signals_html}</tbody>
    </table>

    {ai_html}

    <div class="footer">
        <p>Generado automáticamente por Mi Coche por Dentro — Sistema local multimarca de telemetría OBD-II.</p>
    </div>
</body>
</html>"""
        return ReportGenerator._apply_language(report, language)
